### ISSUE TITLE
Please turn on github pages

### ISSUE THREAD

**Issue by greggman** [esangel/WebGL#10]
Lots of students use these samples and then ask questions on stackoverflow. They have no way to easily include the libraries here in their questions

Click settings then under Github Pages set the Source to "master"

<img width="773" alt="Screen Shot 2019-04-07 at 20 09 35" src="https://user-images.githubusercontent.com/234804/55682647-2812ad80-5971-11e9-82d6-896610e85282.png">

Now students will be able to include the libraries on stackoverflow using

```
<script src="https://esangel.github.io/WebGL/Common/webgl-utils.js"></script>
<script src="https://esangel.github.io/WebGL/Common/initShaders.js"></script>
<script src="https://esangel.github.io/WebGL/Common/MV.js"></script>
```

**Comment by esangel** [comment]
I turned them on. Since we’ve been working on the new edition which uses WebGL 2.0 I haven’t kept up the site. You might also check www.cs.unm.edu/~angel <http://www.cs.unm.edu/~angel> for code and other materials.

Note the pointers at the bottom of your email have my name misspelled. It’s angel not angle.

_______________________

Ed Angel

Founding Director, Art, Research, Technology and Science Laboratory (ARTS Lab)
Professor Emeritus of Computer Science, University of New Mexico

1017 Sierra Pinon
Santa Fe, NM 87501
505-984-0136 (home)		 	angel@cs.unm.edu <mailto:angel@cs.unm.edu>
505-453-4944 (cell) 				http://www.cs.unm.edu/~angel <http://www.cs.unm.edu/~angel>

**Comment by greggman** [comment]
thanks. fixed.
